project:
  type: book
  output-dir: _book
  resources:
    - webr-serviceworker.js
    - webr-worker.js
    - _headers

book:
  title: "Text digitization, recognition and analysis"
  author: "Koen Hufkens"
  date: "2025/01/07"
  page-navigation: true
  chapters:
    - index.qmd
    - intro.qmd
    - digitization.qmd
    - ml_methods.qmd
    - software.qmd
    - project_management.qmd
    - references.qmd
  favicon: "figures/favicon.ico"
  twitter-card: true
  search: true
  repo-url: https://github.com/bluegreen-labs/text_recognition_and_analysis/
  sharing: [twitter, facebook]
  navbar:
    title: ""
    logo: "https://bluegreenlabs.org/img/logo_text_small.png"
    background: "#0b2735"
    search: true
    right:
      - text: "Home"
        file: intro.qmd

bibliography: references.bib

format:
  html:
    theme: 
      light: [cosmo, theme-light.scss]
      dark: [cosmo, theme-dark.scss]
